name: Docker Save To Tar

on:
  workflow_dispatch: # 允许你手动点击按钮触发编译

jobs:
  build-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t hhli/chaos-mesh:latest .

    - name: Save Docker Image to Tar
      run: |
        docker save hhli/chaos-mesh:latest -o chaos-mesh.tar

    - name: Upload Tar Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-tar-file
        path: project-image.tar
        retention-days: 7 # 文件在 GitHub 免费保留 7 天
